import Head from 'next/head'
import Typography from '@mui/material/Typography'

export default function Home() {
  return (
    <>
      <Head>
        <title>Next14 Page Router Demo</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Typography variant='h2'>Next14 Page Router Demo</Typography>
    </>
  )
}
